# Fixtures

fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib"
    concat: "https://github.com/puppetlabs/puppetlabs-concat"
  symlinks:
    vim: "#{source_dir}"

# This
# is
# a
# very
# strange
# buffer
# to
# prevent
# vim
# from
# thinking
# the
# line
# above
# is
# a
# modeline
