language: ruby
script:
  - "bundle exec rake lint"
  - "bundle exec rake spec SPEC_OPTS='--format documentation'"
matrix:
  include:
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0" FACTER_GEM_VERSION="~> 2.4" HIERA_GEM_VERSION="~> 1.3"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0" FACTER_GEM_VERSION="~> 2.4" HIERA_GEM_VERSION="~> 1.3"
  - rvm: 2.1.0
    env: PUPPET_GEM_VERSION="~> 3.0" FACTER_GEM_VERSION="~> 2.4" HIERA_GEM_VERSION="~> 1.3"
  - rvm: 2.1.7
    env: PUPPET_GEM_VERSION="4.3.2" FACTER_GEM_VERSION="~> 2.4" HIERA_GEM_VERSION="~> 3.0"
notifications:
  email: 'zan.loy@gmail.com'
